name = "Forge Creative 1.20"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ab4914f4f0cc629d915e8f64fa52121c78e94d99e50bd30da1244cf244b7cc6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
