peripheraliumVersion = 0.5.6-5
turtlematicVersion = 0.6.3-1
peripheralWorksVersion = 0.4.2-1


peripheralium:
	packwiz url add peripheralium https://mvn.siredvin.site/snapshots/site/siredvin/peripheralium-fabric-1.19.4/$(peripheraliumVersion)/peripheralium-fabric-1.19.4-$(peripheraliumVersion).jar

turtlematic:
	packwiz url add turtlematic https://mvn.siredvin.site/snapshots/site/siredvin/turtlematic-fabric-1.19.4/$(turtlematicVersion)/turtlematic-fabric-1.19.4-$(turtlematicVersion).jar

upw:
	packwiz url add unlimitedperipheralworks https://mvn.siredvin.site/snapshots/site/siredvin/peripheralworks-fabric-1.19.4/$(peripheralWorksVersion)/peripheralworks-fabric-1.19.4-$(peripheralWorksVersion).jar

all: peripheralium turtlematic upw
