name = "Fabric Creative 1.20"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a53d1fea4dc6b4e9587ee5339eb38a77245bf69a45e746039abd9ba958bb29e"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
