name = "Fabric Creative 1.20"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06e69962f3f2f8a2e82f65cf22a1be3b7df0d5d23f6cf4efcf8c090af87aef9d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
