name = "Fabric Creative 1.20"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a562a7575b4d354659a00474e9f9a13c5ceaa0e423fb0f390765f43096dd9a0d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
