cloudsolutionsVersion = 0.3.4
turtlematicVersion = 1.4.9
peripheralWorksVersion = 1.8.0
digitalItemsVersion = 0.5.8
smartHomeAppliancesVersion = 0.1.2

turtlematic:
	packwiz url add turtlematic https://github.com/SirEdvin/Turtlematic/releases/download/v1.21.1-${turtlematicVersion}/turtlematic-fabric-1.21.1-${turtlematicVersion}.jar

upw:
	packwiz url add unlimitedperipheralworks https://github.com/SirEdvin/UnlimitedPeripheralWorks/releases/download/v1.21.1-${peripheralWorksVersion}/peripheralworks-fabric-1.21.1-${peripheralWorksVersion}.jar

digitems:
	packwiz url add digitalitems https://github.com/SirEdvin/DigitalItems/releases/download/v1.21.1-${digitalItemsVersion}/digitalitems-fabric-1.21.1-${digitalItemsVersion}.jar

cloudsolutions:
	packwiz url add cloudsolutions https://github.com/SirEdvin/CloudSolutions/releases/download/v1.21.1-${cloudsolutionsVersion}/cloudsolutions-fabric-1.21.1-${cloudsolutionsVersion}.jar

smarthome:
	packwiz url add smarthome_appliances https://github.com/SirEdvin/SmartHome-Appliances/releases/download/v1.21.1-${smartHomeAppliancesVersion}/smarthome_appliances-fabric-1.21.1-${smartHomeAppliancesVersion}.jar

update:
	packwiz update --all

all: turtlematic upw digitems cloudsolutions smarthome