name = "Fabric Creative 1.21"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4d92e9c7075a0abc3184a9aae5df92c9e0a982fd638c4cd34c8ca706a098f60"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
