name = "Fabric Creative 1 . 21"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9745ed3d5092b82d8c00307ce0c33c0671292cf227bf5e5343b48649a4a9acbb"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
