name = "Fabric Creative 1.21"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3cc15500b3434dc19aec203e0a05a7da7e132a11a1af3e99cf510c260bff5d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
