name = "Fabric Minimal 1.21"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0f25e6b75bd4a933802073597672ae92feb8f983e55097f1cfb09d84b5f8873"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
