name = "Fabric Minimal 1.21"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df337a76ad10a04b370003a7c2f92c1a495a9f592fab33146b283bd7b34c90a0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
