name = "Fabric Minimal 1.21"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50802949b591015182d0ee848d407d4ec9d1bd6d05d3778cd826c843512213a8"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
