name = "NeoForge Creative 1.21"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a292c944c9fa47deb84a88eafdea40ef8c8e31862cd0c62845c72a28362995e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
