name = "NeoForge Creative 1.21"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d4507112d5a8610aeb3a50b092315f5206c4c3d018cb851307d917e2cd0a7a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
