name = "NeoForge Creative 1.21"
author = "SirEdvin"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9231ae3242e0d9de38f1fe5b3426c0c9b758c2eb5b7555e1c730299034fc6d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
