name = "Forge Creative 1 . 20"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2f3dc437727fbb6db515ac6825dee62e37e679103ce5ebb39fc0ac599f5608c"

[versions]
forge = "47.0.1"
minecraft = "1.20"

[options]
acceptable-game-versions = ["1.20"]
