name = "Fabric Creative 1 . 20"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5e572e0a530063e9144afb72e9fdc1fedb7b645988d0201368dceb8147934db"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
