StartupEvents.registry('item', event => {
    event.create('dirty_silica').texture("minecraft:item/quartz").color(0, "#C2B280").displayName("Dirty silica")
    event.create('silica').texture("minecraft:item/quartz").color(0, "#dbd4bf").displayName("Silica")
    event.create("raw_complicated_bulb_0").displayName("Raw Bulb OV")
    event.create("raw_complicated_bulb_1").displayName("Raw Bulb ER")
    event.create("raw_complicated_bulb_2").displayName("Raw Bulb COM")
    event.create("raw_complicated_bulb_3").displayName("Raw Bulb PLI")
    event.create("raw_complicated_bulb_4").displayName("Raw Bulb CA")
    event.create("raw_complicated_bulb_5").displayName("Raw Bulb TED")
    event.create("finished_complicated_bulb_0").displayName("Bulb OV")
    event.create("finished_complicated_bulb_1").displayName("Bulb ER")
    event.create("finished_complicated_bulb_2").displayName("Bulb COM")
    event.create("finished_complicated_bulb_3").displayName("Bulb PLI")
    event.create("finished_complicated_bulb_4").displayName("Bulb CA")
    event.create("finished_complicated_bulb_5").displayName("Bulb TED")
    event.create("unfinished_raw_complicated_bulb", "create:sequenced_assembly").displayName("Unfinished bulb")
    event.create("silicon_wafer").displayName("Silicon Wafer")
    event.create("mechanism_base").displayName("Mechanism base")
    event.create("overcomplicated_mechanism").displayName("Overcomplicated mechanism").color(0, "#a32cc4").texture("create:item/precision_mechanism").glow(true)
})

StartupEvents.registry('fluid', event => {
    event.create("molten_silica").thickTexture(0xdbd4bf)
    .bucketColor(0xdbd4bf)
    .displayName('Molten silica')
})
