name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef9939f809c2d34a7cf932abd5b3b4a2d338b0dfd35a999daed58187a6d8f0c2"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
