name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d96c4b47f93e24a597175773d47d85835e36f2e3199ed193cbdd4b8d3456a4fe"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
