name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a889a165e4320f6cb97713543c69478cb1c91349d3c53e4cba02e9c1081c27e1"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
