name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be33a1be5b714f933bd3a27b0b334bc76be5fd6ea5cdd33d53a7c250923f3a79"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
