name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ed2554a4d5fbefb194deb98b34a026e4a3e7852aa00385e69b67a659c7e6dc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
