name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80c85c0c4c335b770aea718f186dd40d4aa8f10e6ec2076e4435b8e1dcfc2cde"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
