name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a9356c8fa9bf6da9bdc337a906a78251246c9e535a619fe93d6ac26494db1eb"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
