name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cff6c6dd3aa1c00a0f842b69c864affbef1f0499ffc1ad4808e183457079f1ec"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
