name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e00375f2d3c106c3e06bcd97231c27badb099b9906a23fc5fc366a234a936b7"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
