name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b41a358638c71ab3b449b6d4c0eba1f86d4f6bbd3daee3acd3ddb578631e0552"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
