name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5faa35d770730476c0bd362ad3d3581c011480f7aa594d69bde2ac80bf96c146"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
