name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12ae8d8a2ff594b3ba32a11389853eb2dd5afcd75ecd91cd32d544e4c41da0ab"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
