name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d1424066b2727deae0a68648fd6bd723d10938a8cb0aa7f6885f44a9aa376ba"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
