name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d07bdcb7ae05b70d17e6d3cec7c73d181ba794d0b14082c3e22f192eb616133"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
