name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27bb22587bd77d67f47ed79d961379e5cbfbf58d1c8faff28dae8d16e6ed59f1"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
