name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18ed02ccb0b4a74fbbdea811f3f2bee890f7cb08fb845160f238f97689995d84"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
