name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8307470e05bcf0a71c871401ed7bdf183c6fbec3bc8b044643b721647ca7596"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
