name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b403074fcc9f2ad281720f291700172de9c30833ce032a7ce87507a9e0ca01f"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
