name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d00978a933ce182ba3f9a4087a47fb85267b358306e16da36131311bce3a6dc"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
