name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eba87b5a1d000ccaf1cf5ca99a6927ef0c4819e61516c647fd6c6b84469dd67"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
