name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44a7e7852d9da270fd98e68f7692eebae7b97629164db365499c9910b5f7e3e3"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
