name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca6422233fd7f4f5548a1ea8d1956f62d2f5083c6810f6b5cced9fa0c8aec845"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
