name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7999ca28e2b348513314e629a1a066705dddf08c0e29b2870d8377112bb52c19"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
