name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "610865c8d06abf5669a2cd35bf1454094ef67985869b23203e7c0ab08da7e70d"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
