name = "Computerization Zero"
author = "SirEdvin"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "928ccfa197b9708376973025d93d8fe6cb6a7ee4583c29242071dcb2aa8719e3"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
