peripheraliumVersion = 0.4.23
peripheralWorksVersion = 0.2.11


peripheralium:
	packwiz url add peripheralium https://github.com/SirEdvin/Peripheralium/releases/download/v1.19.2-${peripheraliumVersion}/peripheralium-fabric-1.19.2-${peripheraliumVersion}.jar

upw:
	packwiz url add unlimitedperipheralworks https://github.com/SirEdvin/UnlimitedPeripheralWorks/releases/download/v1.19.2-${peripheralWorksVersion}/peripheralworks-fabric-1.19.2-${peripheralWorksVersion}.jar
# digitems:
# 	packwiz url add digitalitems https://github.com/SirEdvin/DigitalItems/releases/download/v1.20.1-${digitalItemsVersion}/digitalitems-fabric-1.20.1-${digitalItemsVersion}.jar
# cloudsolutions:
# 	packwiz url add cloudsolutions https://github.com/SirEdvin/CloudSolutions/releases/download/v1.20.1-${cloudsolutionsVersion}/cloudsolutions-fabric-1.20.1-${cloudsolutionsVersion}.jar

all: peripheralium upw

# modrinth:
# 	packwiz modrinth add peripheralium
# 	packwiz modrinth add unlimitedperipheralworks
# 	packwiz modrinth add turtlematic
