name = "FabCreative-1.19"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b70882e6b00b1a375a56ae3fb053b6eb25c98fb93c92d5cc0702af974a5cfc77"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
