name = "FabCreative-1.19"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dfbbbb44ef1910ff73cc5cbccaef5219e1472359516fd07007353ce613584e0"

[versions]
fabric = "0.14.24"
minecraft = "1.19.2"
