name = "FabCreative-1.19"
author = "SirEdvin"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b655196ee6d65b09738f959df4d482c9aa79b55cf110191a4f6ee51d45079a8"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
